name: "CodeChecks"

on:
  push:
    branches:
      - '**'

    paths:
      - dbus-seplos/**
      - tox.ini

jobs:
  analyse:
    name: Analyze Using GitHub CodeQL
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: "3.8.13"

    - name: Clone velib_python and add it to PYTHONPATH for subsequent steps
      run: |
        git clone https://github.com/victronenergy/velib_python.git
        echo PYTHONPATH=$PYTHONPATH:$(pwd)/velib_python >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        pip install -r dbus-seplos/requirements.txt
        flake8 dbus-seplos
