############################################################
# -*- coding: utf-8 -*-
#
#  o-o   o--o  o   o  o-o
#  |  \  |   | |   | |
#  |   O O--o  |   |  o-o
#  |  /  |   | |   |     |
#  o-o   o--o   o-o  o--o
#
#
#   o-o  o--o o--o  o     o-o   o-o
#  |     |    |   | |    o   o |
#   o-o  O-o  O--o  |    |   |  o-o
#      | |    |     |    o   o     |
#  o--o  o--o o     O---o o-o  o--o
#
# python-based service for victron cerbo > v3.00
#
# (c) 2024 by mworion
# Licence MIT
#
###########################################################
name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: install drawio package
        run: |
          sudo apt update
          sudo apt install snapd
          sudo snap install drawio
        
      - name: Install python dependencies
        run: |
          pip install sphinx sphinx_rtd_theme alabaster sphinx-copybutton
          pip install setuptools sphinxcontrib-drawio sphinx-simplepdf
          
      - name: Sphinx build
        run: |
          sphinx-build doc doc/html
          sphinx-build -M simplepdf doc doc/pdf
          cp doc/pdf/simplepdf/*.pdf doc/html
          mv doc/pdf/simplepdf/*.pdf doc/html/dbus-seplos.pdf

      - name: check files
        run: |
          ls -la
          ls -la doc/pdf
          ls -la doc/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc/build
          force_orphan: true
