############################################################
# -*- coding: utf-8 -*-
#
#  o-o   o--o  o   o  o-o
#  |  \  |   | |   | |
#  |   O O--o  |   |  o-o
#  |  /  |   | |   |     |
#  o-o   o--o   o-o  o--o
#
#
#   o-o  o--o o--o  o     o-o   o-o
#  |     |    |   | |    o   o |
#   o-o  O-o  O--o  |    |   |  o-o
#      | |    |     |    o   o     |
#  o--o  o--o o     O---o o-o  o--o
#
# python-based service for victron cerbo > v3.00
#
# (c) 2025 by mworion
# Licence MIT
#
###########################################################

name: BuildRelease

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true
  
on:
  push:
    tags:
      # do not match pre release
      # matches:
      # v1.0.0
      # v1.0.123
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: build release archive
        run: |
          find . -type f -name "*.py" -exec chmod +x {} \;
          find . -type f -name "*.sh" -exec chmod +x {} \;
          find . -type f -name "run" -exec chmod +x {} \;
          tar -czvf dbus-seplos.tar.gz \
            --mode='a+rwX' \
            --exclude __pycache__ \
            --exclude test_*.py \
          dbus-seplos
          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dbus-seplos.tar.gz
